version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  browser-tools: circleci/browser-tools@1.2.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup  
      - browser-tools/install-chrome
      #install, build, test and deploy the backend app to Elastik Beanstalk
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      # - run:
      #     name: Back-End Test
      #     command: 
      #       npm run backend:test    
      #install, test, build and deploy the frontend app to S3
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test      
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End Test
          command: |
            npm run backend:test    